[project]
name = "mcmultiblocks"
version = "0.0.0" # This version get's automatically assigned when creating a release
authors = [
  { name="ShelfHead"},
  { name="TheBlackSwitch"}
]
description = "Multiblocks library"
readme = "README.md"
requires-python = ">=3.14"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-or-later"
license-files = ["LICENCSE"]
dependencies = [
    "nbtlib>=1.12",
    "beet>=0.113.0"
]


[project.urls]
Homepage = "https://github.com/KobeMotmans/Multiblocks"
Issues = "https://github.com/KobeMotmans/Multiblocks/issues"
