[project]
name = "mcmultiblocks_ShelfHead"
version = "0.1.4"
authors = [
  { name="ShelfHead"},
  { name="TheBlackSwitch"}
]
description = "Multiblocks library"
readme = "README.md"
requires-python = ">=3.14"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICENCSE"]
dependencies = [
    "nbtlib>=1.12",
    "beet>=0.113.0"
]


[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"